// Make a html tables with times and dates Free by the selected room
var sideBarContent0 = 
`<table>
    <tr>
        <th>Time</th>
        <th>Status</th>
    </tr>
    <tr>
        <td>05:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>06:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>07:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>08:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>09:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>10:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>11:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>12:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>13:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>14:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>15:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>16:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>17:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>18:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>19:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>20:00</td>
        <td>Free</td>
    </tr>

</table>`;

var sideBarContent1 = 
`<table>
    <tr>
        <th>Time</th>
        <th>Status</th>
    </tr>
    <tr>
        <td>05:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>06:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>07:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>08:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>09:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>10:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>11:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>12:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>13:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>14:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>15:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>16:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>17:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>18:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>19:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>20:00</td>
        <td>Free</td>
    </tr>

</table>`;


var sideBarContent2 = 
`<table>
    <tr>
        <th>Time</th>
        <th>Status</th>
    </tr>
    <tr>
        <td>05:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>06:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>07:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>08:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>09:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>10:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>11:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>12:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>13:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>14:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>15:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>16:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>17:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>18:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>19:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>20:00</td>
        <td>Free</td>
    </tr>

</table>`;

var sideBarContent3 = 
`<table>
    <tr>
        <th>Time</th>
        <th>Status</th>
    </tr>
    <tr>
        <td>05:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>06:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>07:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>08:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>09:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>10:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>11:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>12:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>13:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>14:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>15:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>16:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>17:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>18:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>19:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>20:00</td>
        <td>Occupied</td>
    </tr>

</table>`;



var sideBarContentOverall0 = 
`<table>
    <tr>
        <th>Day</th>
        <th>Occupancy</th>
    </tr>
    <tr>
        <td>Monday</td>
        <td>60%</td>
    </tr>
    <tr>
        <td>Tuesday</td>
        <td>80%</td>
    </tr>
    <tr>
        <td>Wednesday</td>
        <td>95%</td>
    </tr>
    <tr>
        <td>Thursday</td>
        <td>55%</td>
    </tr>
    <tr>
        <td>Friday</td>
        <td>50%</td>
    </tr>
    <tr>
        <td>Saturday</td>
        <td>10%</td>
    </tr>
    <tr>
        <td>Sunday</td>
        <td>10%</td>
    </tr>
</table>`;

var sideBarContentOverall1 = 
`<table>
    <tr>
        <th>Day</th>
        <th>Occupancy</th>
    </tr>
    <tr>
        <td>Monday</td>
        <td>70%</td>
    </tr>
    <tr>
        <td>Tuesday</td>
        <td>90%</td>
    </tr>
    <tr>
        <td>Wednesday</td>
        <td>100%</td>
    </tr>
    <tr>
        <td>Thursday</td>
        <td>65%</td>
    </tr>
    <tr>
        <td>Friday</td>
        <td>75%</td>
    </tr>
    <tr>
        <td>Saturday</td>
        <td>20%</td>
    </tr>
    <tr>
        <td>Sunday</td>
        <td>20%</td>
    </tr>
</table>`;

var sideBarContentOverall2 = 
`<table>
    <tr>
        <th>Day</th>
        <th>Occupancy</th>
    </tr>
    <tr>
        <td>Monday</td>
        <td>80%</td>
    </tr>
    <tr>
        <td>Tuesday</td>
        <td>80%</td>
    </tr>
    <tr>
        <td>Wednesday</td>
        <td>90%</td>
    </tr>
    <tr>
        <td>Thursday</td>
        <td>75%</td>
    </tr>
    <tr>
        <td>Friday</td>
        <td>85%</td>
    </tr>
    <tr>
        <td>Saturday</td>
        <td>25%</td>
    </tr>
    <tr>
        <td>Sunday</td>
        <td>25%</td>
    </tr>
</table>`;
var sideBarContentOverall3 = 
`<table>
    <tr>
        <th>Day</th>
        <th>Occupancy</th>
    </tr>
    <tr>
        <td>Monday</td>
        <td>100%</td>
    </tr>
    <tr>
        <td>Tuesday</td>
        <td>95%</td>
    </tr>
    <tr>
        <td>Wednesday</td>
        <td>95%</td>
    </tr>
    <tr>
        <td>Thursday</td>
        <td>80%</td>
    </tr>
    <tr>
        <td>Friday</td>
        <td>95%</td>
    </tr>
    <tr>
        <td>Saturday</td>
        <td>60%</td>
    </tr>
    <tr>
        <td>Sunday</td>
        <td>60%</td>
    </tr>
</table>`;

