// Make a html tables with times and dates Free by the selected room
var sideBarContent0 = 
`<table>
    <tr>
        <th>Time</th>
        <th>Status</th>
    </tr>
    <tr>
        <td>05:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>06:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>07:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>08:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>09:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>10:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>11:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>12:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>13:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>14:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>15:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>16:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>17:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>18:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>19:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>20:00</td>
        <td>Free</td>
    </tr>

</table>`;

var sideBarContent1 = 
`<table>
    <tr>
        <th>Time</th>
        <th>Status</th>
    </tr>
    <tr>
        <td>05:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>06:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>07:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>08:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>09:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>10:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>11:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>12:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>13:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>14:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>15:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>16:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>17:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>18:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>19:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>20:00</td>
        <td>Free</td>
    </tr>

</table>`;


var sideBarContent2 = 
`<table>
    <tr>
        <th>Time</th>
        <th>Status</th>
    </tr>
    <tr>
        <td>05:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>06:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>07:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>08:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>09:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>10:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>11:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>12:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>13:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>14:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>15:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>16:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>17:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>18:00</td>
        <td>Free</td>
    </tr>
    <tr>
        <td>19:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>20:00</td>
        <td>Free</td>
    </tr>

</table>`;

var sideBarContent3 = 
`<table>
    <tr>
        <th>Time</th>
        <th>Status</th>
    </tr>
    <tr>
        <td>05:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>06:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>07:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>08:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>09:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>10:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>11:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>12:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>13:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>14:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>15:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>16:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>17:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>18:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>19:00</td>
        <td>Occupied</td>
    </tr>
    <tr>
        <td>20:00</td>
        <td>Occupied</td>
    </tr>

</table>`;